### ISSUE TITLE
اشکال کد chronograph

### ISSUE THREAD

**Issue by yasaman-loghmani** [dibagaran/js-2015-8-alpha#1]
salam code js choronograph line 39 eshtebah ast 

bejaye running = false;   meghdar running bayad true bashad . chon meghdar avalie an false ast va pas az start meghdar an true mishavad . pas zamani stop mishavad ke meghdar an true bashad .

**Comment by meysam-mousavi** [comment]
Line 39 refers to 'Reset' button which means the chronograph should be stopped and set back to zero. Every time we clear the interval we set the flag to false which means the chronograph is not running anymore so the code is fine.
